services:
    db:
        hostname: db
        image: mysql:5.7
        restart: always
        volumes:
            - ./volumes/mysql-init:/docker-entrypoint-initdb.d
            # - ./volumes/mysql-data:/var/lib/mysql
        networks:
            backend-net:
                ipv4_address: 172.25.1.2
        environment: 
            MYSQL_ROOT_PASSWORD: qwerty
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pqwerty | grep 'mysqld is alive' || exit 1"]
            interval: 5s       # cada cuánto se ejecuta el chequeo
            timeout: 5s        # tiempo máximo de espera por respuesta
            retries: 5         # cuántas veces se intenta antes de marcar unhealthy
            start_period: 10s  # tiempo de gracia antes del primer test

    ldap:
        hostname: ldap
        image: cbernabel/openldap-fly:v1
#        volumes:
#          - ./volumes/ldap-script:/opt/script
#          - ./volumes/ldap-conf:/etc/ldap/slapd.d
#          - ./volumes/ldap-data:/var/lib/ldap
        ports:
          - "389:389"
        networks:
            backend-net:
                ipv4_address: 172.25.1.3
        environment: 
            BIND_PASSWORD: qwerty

    imap:
        hostname: imap
        image: cbernabel/dovecot-fly:v1
        ports:
          - "143:143"
          - "993:993"
        networks:
            backend-net:
                ipv4_address: 172.25.1.4
        depends_on:
            db:
              condition: service_healthy

    app:
        hostname: app 
        image: cbernabel/roundcube-fly:v1
        restart: always
        volumes:
             - ./volumes/app-data/ssl:/etc/ssl
        working_dir: /root
        ports:
             - 80:80
        networks:
            backend-net:
                ipv4_address: 172.25.1.5
        environment:
            MYSQL_HOST: db
            MYSQL_USER: admin
            MYSQL_PASSWORD: querty
            MYSQL_DB: roundcubemail
        depends_on:
            db:
              condition: service_healthy

    smtp:
        hostname: smtp
        image: cbernabel/postfix-fly:v1
        restart: always
        environment:
          - MAIL_DOMAIN=valhalla.es
          - MAIL_RELAY_NETWORKS=172.25.1.0/24
        ports:
          - "25:25"
          - "587:587"
        networks:
            backend-net:
                ipv4_address: 172.25.1.6
#        volumes:
#          - ./postfix/main.cf:/etc/postfix/main.cf
#          - ./postfix/master.cf:/etc/postfix/master.cf
#          - ./postfix/ldap-users.cf:/etc/postfix/ldap-users.cf
#          - ./postfix/ldap-aliases.cf:/etc/postfix/ldap-aliases.cf
        depends_on:
          - imap

#    dirserv:
#        hostname: dirserv
#        image: dirserv-fly
#        volumes:
#            - ./volumes/ldap-script:/opt/script
##          - ./volumes/ldap-conf:/etc/ldap/slapd.d
##          - ./volumes/ldap-data:/var/lib/ldap
#        networks:
#            backend-net:
#                ipv4_address: 172.25.1.6
#        environment: 
#            BIND_PASSWORD: qwerty
#
networks:
    backend-net:
        ipam:
            driver: default
            config: 
                - subnet: 172.25.1.0/24
